storage:
 value: default
 wizard:
   name: "Storage Configuration"
   kind: cluster_storage

pytorch_version:
  value: "1.4.0"
  wizard:
    name: "PyTorch version"
    kind: select
    options:
    - "1.3.1"
    - "1.4.0"

tensorboard:
  value: false
  wizard:
    name: Install Tensorboard
    kind: boolean

dataset:
  value: ''
  version: ''
  workspace: ''
  wizard:
    name: "Dataset configuration"
    kind: dataset

# Pip packages may be specified here in format that pip accepts.
packages: []
